# Site
name: "Imamo pravo znati akcije i kampanje"
title: "Imamo pravo znati - akcije i kampanje"
description: "ImamoPravoZnati.org akcije i kampanje"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /
google_analytics: 'UA-xxxxxxxx-1'
mailchimp-list: 'https://codeforcroatia.us3.list-manage.com/subscribe/post?u=6fda5cd904a423904e039bb6e&amp;id=2f0ec27e18'
include: ["_pages"]
permalink: /:title/

# Contact us form (Formspree.io)
email: wowthemesnet@gmail.com

# Authors
authors:
  cfc:
    name: Code for Croatia
    display_name: Code for Croatia
    avatar: 'assets/images/avatar-sal.png'
    email:
    web: https://codeforcroatia.org
    twitter: https://twitter.com/codeforcroatia
    description: "Promičemo otvorene tehnologije u službi građana te povećanje transparentnosti javne uprave u svrhu poboljšanja civilnog društva."
  gong:
    name: Gong
    display_name: Gong
    avatar: 'assets/images/avatar.png'
    email: 
    web: https://gong.hr
    twitter: https://twitter.com/gong_hr
    description: "Gong je megafon demokracije: ometa korupciju, upozorava na političke ugroze i gradi ravnopravno građanstvo."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true

# Comments

## Disqus (uncomment below and add disqus id)
#disqus: ''

## Discourse (enabled when it's set to true; disable if it's set to false; enter Discourse domain in URL with trailing slash "/")
discourse: true
discourse-url: 'https://codeforcroatia.org/'

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
